---
- name: start an instance with a public IP address
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create EC2
  amazon.aws.ec2_instance:
  	name: "CA4-ansibleinstance"
        key_name: "yashepam"
        vpc_subnet_id: subnet-0ece4fa4b3197ee1c
        instance_type: t2.micro
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-02eb7a4783e7e9317
        state: running
        tags:
          Environment: Testing
