- hosts: localhost
  gather_facts: True
  check_mode: no
  tasks:
  - name: Add public ip addresses to an dynamic inventory
    add_host:
      name: "{{ host }}"
      groups: all

  - local_action: wait_for port=22 host="{{ host }}" search_regex=OpenSSH delay=10

- hosts: all
  gather_facts: False
  check_mode: no
  become: True
  tasks:
  - name: Install python 2.7
    raw: >
      test -e /usr/bin/python ||
      (
        (test -e /usr/bin/apt-get && (apt-get -y update && apt-get install -y python)) ||
        (test -e /usr/bin/yum && (yum makecache fast && yum install -y python))
      )
    args:
      creates: /usr/bin/python

- hosts: localhost
  gather_facts: True
  check_mode: no
  tasks:
  - name: run ssh-keyscan to add keys to known_hosts
    local_action: shell ssh-keyscan "{{ host }}" >> ~/.ssh/known_hosts
  - name: Add public ip addresses to an dynamic inventory
    add_host:
      name: "{{ host }}"
      groups: all

  - local_action: wait_for port=22 host="{{ host }}" search_regex=OpenSSH delay=10

- hosts: all
  vars:
     ansible_python_interpreter: "/usr/bin/python"
     ANSIBLE_HOST_KEY_CHECKING: "False"
  gather_facts: no
  become: true
  become_user: root
  check_mode: no
  tasks:
  - name: Upload docker-compose files
    synchronize: 
      src: ../../prometheus-docker
      dest: /var/tmp/

  - name: apt-get clean
    shell: apt-get clean
   
