version: '3'

services:
  nginx-with-static-ip:
    image: nginx:latest
    container_name: nginx_container
    networks:
      nginx_network:
        ipv4_address: 172.40.0.2
    ports:
      - "8080:80"
    restart: always

networks:
  nginx_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16
          gateway: 172.40.0.1
