---
- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_type: t2.micro
    ami: ami-07d3a50bd29811cd1
    region: ap-south-1
    key_name: yashepam
    security_group: launch-wizard-1
    tag_name: ansibleEc2
  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        region: "{{ region }}"
        group: "{{ security_group }}"
        instance_tags:
          Name: "{{ tag_name }}"
        wait: true
      register: ec2

    - name: Print Public IP Address
      debug:
        msg: "Instance IP address is {{ ec2_instance.instances[0].public_ip }}"
